"use client";
import {useState} from "react";
import {Phone,MessageCircle,MapPin,Clock3,Satellite,Tv,Cctv,Wrench,Menu,X,ChevronRight,CheckCircle2,AlertTriangle,Navigation,UserRound} from "lucide-react";
const PHONE="tel:+905359447662", WA="https://wa.me/905359447662?text=Merhaba%20Erdal%20Usta%2C%20teknik%20servis%20hakk%C4%B1nda%20bilgi%20almak%20istiyorum.", MAP="https://www.google.com/maps/place//data=!4m2!3m1!1s0x1527f33d86cfc2dd:0x31442eb78614a04c";
type D={tag:string,title:string,intro:string,type:"sat"|"tv"|"cam"|"tool",issues:string[],scope:string[],safety:string,faq:[string,string][]};
const common={faq:[["Servis talebi ne zaman oluşturabilirim?","Haftanın 7 günü, 24 saat telefon veya WhatsApp üzerinden talep bırakabilirsiniz."],["Telefonda kesin fiyat veriliyor mu?","Belirtiye göre ön bilgi verilir; kesin işlem ve parça ihtiyacı kontrol sonrası netleşir."]] as [string,string][]};
export const pages:Record<string,D>={
home:{tag:"TOROSLAR MERKEZLİ YERİNDE SERVİS",title:"Mersin’de uydu, televizyon ve kamera teknik servisi",intro:"Erdal Usta; Toroslar, Akdeniz, Yenişehir ve Mezitli’de arızayı dinler, uygun servis planını açıkça anlatır ve adresinize gelir.",type:"tool",issues:["Uydu sinyali yok veya kanallar eksik","Televizyonda ses var, görüntü yok","Ev ve iş yeri kamera kurulumu"],scope:["Uydu ve çanak anten","Televizyon tamiri","Güvenlik kamerası sistemleri"],safety:"Elektrikle ilgili cihazları açmayın. Fişi güvenle çekebiliyorsanız çekin ve arızayı Erdal Usta’ya anlatın.",...common},
"mersin-uyducu":{tag:"UYDU VE ÇANAK ANTEN",title:"Mersin uyducu ve yerinde uydu servisi",intro:"Sinyal kaybı, kanal eksikliği, çanak yönü, LNB, kablo ve merkezi sistem sorunlarında doğru müdahaleyi planlıyoruz.",type:"sat",issues:["Sinyal yok / zayıf sinyal uyarısı","Bazı kanalların göstermemesi","Rüzgâr sonrası çanak yönünün değişmesi","Uydu kablosu ve bağlantı arızaları"],scope:["Sinyal ölçümü","Çanak anten montajı ve ayarı","LNB ve kablo kontrolü","Uydu alıcısı kurulum desteği"],safety:"Çatıya, dış cepheye veya ıslak zemine çıkmayın. Erişimi riskli antenlere uygun ekipmanla müdahale edilmelidir.",faq:[["Uydu neden birden sinyal vermez?","Kablo teması, LNB arızası, çanak yönü veya merkezi sistem kaynaklı olabilir."],...common.faq]},
"mersin-televizyon-tamiri":{tag:"ÖZEL TEKNİK SERVİS",title:"Mersin televizyon tamiri ve TV arıza tespiti",intro:"Televizyon açılmıyor, görüntü gelmiyor veya ses sorunu yaşanıyorsa cihazı açmadan güvenli destek isteyin.",type:"tv",issues:["Ses var görüntü yok","Televizyon hiç açılmıyor","Görüntü gidip geliyor","HDMI veya yayın görüntüsü gelmiyor"],scope:["Belirtiye göre ön değerlendirme","Güç ve bağlantı kontrolü","Görüntü ve ses arızası tespiti"],safety:"Televizyonun arka kapağını açmayın. Fiş çekilmiş olsa bile iç devrelerde tehlikeli gerilim kalabilir.",faq:[["Ses var ama görüntü yoksa ne yapmalıyım?","Cihazı kapatıp servisle görüşün; tekrar tekrar açmak arızayı büyütebilir."],...common.faq]},
"mersin-kamera-sistemleri":{tag:"GÜVENLİK KAMERASI",title:"Mersin kamera sistemleri ve güvenlik kamerası kurulumu",intro:"Ev, apartman ve iş yerleri için görüş alanı, gece görüntüsü, kayıt süresi ve uzaktan izleme ihtiyacına göre kurulum planı çıkarıyoruz.",type:"cam",issues:["Yeni kamera sistemi kurulumu","Kayıt cihazında görüntü yok","Telefondan izleme sorunu","Kablo ve adaptör arızaları"],scope:["Keşif değerlendirmesi","Kamera konumu ve görüş açısı","Kayıt cihazı bağlantıları","Uzaktan izleme kurulumu"],safety:"Kamera konumları özel alanları ihlal etmemeli; yüksek noktalardaki montaj uzman ekipmanıyla yapılmalıdır.",faq:[["Kaç kamera gerekir?","Girişler, kör noktalar ve kayıt beklentisi görülmeden sayı söylemek doğru olmaz."],...common.faq]},
"uydu-sinyal-yok":{tag:"ARIZA REHBERİ",title:"Uydu sinyal yok sorunu: güvenli kontroller",intro:"Önce sorunun tek televizyonda mı, binadaki tüm dairelerde mi olduğunu belirleyin.",type:"sat",issues:["Tüm kanallarda sinyal yok","Hava sonrası kesinti","Bazı kanallar eksik"],scope:["Kablo ayrımı","Sinyal ölçümü","LNB ve çanak kontrolü"],safety:"Çatıya çıkmayın veya dış cephedeki antene uzanmayın.",...common},
"canak-anten-montaji":{tag:"KURULUM",title:"Mersin çanak anten montajı ve hassas yön ayarı",intro:"Sağlam sabitleme, açık görüş hattı ve doğru ölçüm uzun süre kararlı yayın için gereklidir.",type:"sat",issues:["Yeni anten ihtiyacı","Taşınma sonrası kurulum","Paslı bağlantı elemanları"],scope:["Konum değerlendirmesi","Montaj ve kablolama","Ölçümle yön ayarı"],safety:"Dış cephe ve çatı montajı düşme riski taşır; kişisel müdahale etmeyin.",...common},
"merkezi-uydu-sistemleri":{tag:"ORTAK SİSTEMLER",title:"Mersin merkezi uydu sistemi arıza servisi",intro:"Apartmanlarda sorun daire hattı, priz, multiswitch veya ortak antende olabilir; ölçümle doğru ayrım yapılır.",type:"sat",issues:["Tek dairede yayın yok","Birden çok dairede kesinti","Bazı frekanslar eksik"],scope:["Daire hattı kontrolü","Multiswitch değerlendirmesi","Sinyal ölçümü"],safety:"Ortak pano ve çatı ekipmanına bina sorumlusunun bilgisi olmadan dokunmayın.",...common},
"tv-ses-var-goruntu-yok":{tag:"TV ARIZA REHBERİ",title:"TV’de ses var görüntü yok: olası nedenler",intro:"Ekran karanlıksa kaynak seçimi, bağlantı veya ekran aydınlatması gibi farklı nedenler olabilir.",type:"tv",issues:["Ekran karanlık","Görüntü gelip gidiyor","Menü görünmüyor"],scope:["Kaynak ve HDMI ayrımı","Işık ve görüntü kontrolü","Arıza değerlendirmesi"],safety:"Arka kapağı açmayın; yüksek gerilim riski vardır.",...common},
"televizyon-acilmiyor":{tag:"TV ARIZA REHBERİ",title:"Televizyon açılmıyor: önce ne kontrol edilmeli?",intro:"Priz, kumanda pili ve güç kablosunu kontrol edin. Yanık kokusu veya hasarlı kablo varsa cihazı kullanmayın.",type:"tv",issues:["Bekleme ışığı yanmıyor","Işık var ekran açılmıyor","Açılıp kapanıyor"],scope:["Harici güç kontrolü","Belirti ayrımı","Servis planı"],safety:"Yanık kokusu veya kıvılcım varsa enerjiyi güvenle kesin ve yardım alın.",...common},
"guvenlik-kamerasi-kurulumu":{tag:"KURULUM REHBERİ",title:"Güvenlik kamerası kurulumu nasıl planlanır?",intro:"Doğru sistem; girişleri ve kritik alanları uygun açıyla gören, ihtiyaca uygun kayıt tutan sistemdir.",type:"cam",issues:["Kör noktalar","Yetersiz gece görüntüsü","Kısa kayıt süresi"],scope:["Görüş alanı planı","Kablo güzergâhı","Kayıt ve uzaktan erişim"],safety:"Komşu mülkler ve mahrem alanlar görüntülenmemelidir.",...common},
hakkimizda:{tag:"İBİN ELEKTRONİK",title:"Erdal Usta ile yerel ve ulaşılabilir teknik servis",intro:"İbin Elektronik, Toroslar merkezli olarak uydu, televizyon ve kamera alanlarında müşterinin adresine giden özel teknik servistir.",type:"tool",issues:["Sorunu doğrudan dinleme","Uygun servis planı","İşlem kapsamını açıklama"],scope:["Toroslar","Akdeniz","Yenişehir","Mezitli"],safety:"Marka yetkili servisi iddiası olmadan yerel özel teknik servis olarak hizmet verilir.",...common},
iletisim:{tag:"SERVİS TALEBİ",title:"İbin Elektronik iletişim ve yol tarifi",intro:"Arızanın fotoğrafını WhatsApp’tan gönderin veya Erdal Usta’yı arayın. Adresinize göre servis planı oluşturulsun.",type:"tool",issues:["0535 944 76 62","Selçuklar Mahallesi, Çiftçiler Caddesi","33250 Toroslar / Mersin"],scope:["Telefonla ön bilgi","WhatsApp’tan fotoğraf","Google Haritalar yol tarifi"],safety:"Acil elektrik tehlikesinde enerjiyi güvenle kesin; müdahale etmeyin.",...common},
"sikca-sorulan-sorular":{tag:"MERAK EDİLENLER",title:"Teknik servis sıkça sorulan sorular",intro:"Servis alanı, fiyatlandırma, güvenli kontroller ve randevu süreci hakkında açık yanıtlar.",type:"tool",issues:["Fiyat nasıl belirlenir?","Hangi bölgelerde servis var?","Ne zaman usta çağırmalıyım?"],scope:["Uydu servisi","TV arızası","Kamera kurulumu"],safety:"Elektrik ve yüksekte çalışma riski bulunan işlemleri kendiniz denemeyin.",...common}}
const nav=[["Uydu Servisi","mersin-uyducu"],["TV Tamiri","mersin-televizyon-tamiri"],["Kamera Sistemleri","mersin-kamera-sistemleri"],["Hakkımızda","hakkimizda"],["İletişim","iletisim"]]; const icons={sat:Satellite,tv:Tv,cam:Cctv,tool:Wrench};
export default function SitePage({slug}:{slug:string}){const[open,setOpen]=useState(false),p=pages[slug]||pages.home,Icon=icons[p.type],home=slug==="home";return <div>
<div className="top"><span><MapPin/> Toroslar merkezli yerinde servis</span><span><Clock3/> 7 gün 24 saat servis talebi</span></div><header><a className="brand" href="/"><b>İBİN</b> ELEKTRONİK<small>Erdal Usta</small></a><nav>{nav.map(x=><a key={x[1]} href={'/'+x[1]}>{x[0]}</a>)}</nav><a className="call" href={PHONE}><Phone/>0535 944 76 62</a><button onClick={()=>setOpen(!open)} aria-label="Menü">{open?<X/>:<Menu/>}</button>{open&&<div className="mobile">{nav.map(x=><a key={x[1]} href={'/'+x[1]}>{x[0]}<ChevronRight/></a>)}</div>}</header>
<main><section className="hero"><div><p className="tag">{p.tag}</p><h1>{p.title}</h1><p className="intro">{p.intro}</p><div className="actions"><a href={PHONE}><Phone/>Erdal Usta’yı Ara</a><a className="wa" href={WA}><MessageCircle/>WhatsApp’tan Arızayı Gönder</a></div><div className="proof"><span><CheckCircle2/>Yerinde servis</span><span><CheckCircle2/>Açık bilgilendirme</span></div></div><aside><div className="radar"><Icon/></div><small>SERVİS HATTI</small><strong>0535 944 76 62</strong><p>Arızayı anlatın, uygun servis planını birlikte oluşturalım.</p><i>● Servis talebi açık</i></aside></section>
{home&&<section className="services">{[[Satellite,"Uydu servisi","Sinyal, çanak, LNB ve merkezi sistem sorunları.","mersin-uyducu"],[Tv,"Televizyon servisi","Görüntü, ses ve açılmama arızaları.","mersin-televizyon-tamiri"],[Cctv,"Kamera sistemleri","Ev ve işletmeler için planlı kurulum.","mersin-kamera-sistemleri"]].map(([I,t,d,u]:any)=><article key={u}><I/><h2>{t}</h2><p>{d}</p><a href={'/'+u}>İncele <ChevronRight/></a></article>)}</section>}
<section className="content"><div><p className="tag">NELERİ KONTROL EDİYORUZ?</p><h2>Belirtiler ve hizmet kapsamı</h2><p className="intro">Önce belirtinin kaynağını ayırır, yapılacak işlemi anlaşılır biçimde açıklarız.</p><div className="issues">{p.issues.map((x,i)=><p key={x}><b>0{i+1}</b>{x}</p>)}</div></div><aside><h3>Hizmet kapsamı</h3>{p.scope.map(x=><p key={x}><CheckCircle2/>{x}</p>)}<a href={PHONE}>Telefonla ön bilgi alın <ChevronRight/></a></aside></section>
<section className="process"><p className="tag">NASIL İLERLİYORUZ?</p><h2>Üç adımda servis talebi</h2><div>{[[Phone,"Arızayı anlatın","Cihaz ve belirti hakkında kısa bilgi verin."],[Navigation,"Planlama yapılsın","Konum ve servis zamanı netleşsin."],[Wrench,"Yerinde kontrol","İşlem kapsamı açıkça anlatılsın."]].map(([I,t,d]:any)=><article key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="safety"><AlertTriangle/><div><b>GÜVENLİK NOTU</b><h2>Kendinizi riske atmayın</h2><p>{p.safety}</p></div></section>
{home&&<section className="areas"><div><p className="tag">SERVİS BÖLGELERİ</p><h2>Toroslar’dan merkez ilçelere</h2><p className="intro">İbin Elektronik müşterinin adresine gider. Zamanlama konum ve yoğunluğa göre yapılır.</p></div><div>{["Toroslar — Merkez","Akdeniz — Yerinde servis","Yenişehir — Yerinde servis","Mezitli — Yerinde servis"].map(x=><p key={x}>{x}</p>)}</div></section>}
<section className="faq"><p className="tag">SIKÇA SORULAN SORULAR</p><h2>Karar vermeden önce bilin</h2>{p.faq.map(([q,a])=><details key={q}><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</section>
<section className="cta"><div><small>ŞİMDİ İLETİŞİME GEÇİN</small><h2>Arızayı bekletmeyin, Erdal Usta’ya ulaşın</h2></div><div className="actions"><a href={PHONE}><Phone/>0535 944 76 62</a><a className="wa" href={WA}><MessageCircle/>WhatsApp’tan Yaz</a></div></section></main>
<footer><div><div className="brand"><b>İBİN</b> ELEKTRONİK</div><p>Mersin’de uydu, televizyon ve kamera için yerel özel teknik servis.</p></div><div><h3>Hizmetler</h3>{nav.slice(0,3).map(x=><a key={x[1]} href={'/'+x[1]}>{x[0]}</a>)}</div><div><h3>İletişim</h3><a href={PHONE}>0535 944 76 62</a><a href={WA}>WhatsApp</a><a href={MAP}>Selçuklar Mah., Çiftçiler Cad.<br/>33250 Toroslar/Mersin</a></div><small>© 2026 İbin Elektronik</small></footer><div className="bar"><a href={PHONE}><Phone/>Ara</a><a href={WA}><MessageCircle/>WhatsApp</a></div></div>}
